import os
os.system('> webpage.html')
file = open("web.html")
line = file.read()
file.close()
line = line.replace('?()', '<')
line = line.replace('?)(', '>')
line = line.replace('$+=', '/')
line = line.replace('$=+', '{')
line = line.replace('$$$', '}')
line = line.replace('$--', '[')
line = line.replace('$+-', ']')
line = line.replace('$+$', '&')
line = line.replace('$=$', '|')
line = line.replace('$@$', '~')
line = line.replace('$-$', '#')
line = line.replace('$p$', '%')
line = line.replace('$!$', '*')
#line = line.replace('$"$', '<a href=')
#line = line.replace('t', 'the')
#line = line.replace(' f ', 'for')
#line = line.replace(' w ', 'with')
#line = line.replace('$a$', 'aria-hidden')
#line = line.replace('$t$', 'this')
#line = line.replace('$n$', 'noscript')
#line = line.replace('$s$', 'script')
#line = line.replace('$m$', '<meta')
#line = line.replace('$b$', '<blockquote>')
#line = line.replace("$'$", "</a>")
#line = line.replace("$st$", "</script>")
line = line.lower()
print(line)
