import os
import subprocess
request = input('Webpage request: ')
os.system('wget %s -q -O - > sourceorig.html' % request)
encoding = subprocess.check_output("file --mime-encoding sourceorig.html | sed -n -e 's/^.*sourceorig.html: //p'", shell=True) 
encoding = encoding.decode('utf-8')
encoding = encoding.strip()
os.system('iconv -f %s -t utf-8 sourceorig.html -o source.html' % encoding)
os.system("sed '/<head>/,/<\/head>/{//!d}' source.html > encode.html")
file = open("encode.html","r")
page_source = file.read()
file.close()
#page_source = "<!DOCTYPE html><html><body><h1>My First Heading</h1><p>My first paragraph.</p></body></html><!DOCTYPE html>"
# Stripping down the HTML to its essentials
page_source = page_source.lower()
page_source = page_source.replace('\n', '')
page_source = page_source.replace('<', '?()')
page_source = page_source.replace('>', '?)(')
page_source = page_source.replace('/', '$+=')
page_source = page_source.replace('{', '$=+')
page_source = page_source.replace('}', '$$$')
page_source = page_source.replace('[', '$--')
page_source = page_source.replace(']', '$+-')
page_source = page_source.replace('&', '$+$')
page_source = page_source.replace('|', '$=$')
page_source = page_source.replace('~', '$@$')
page_source = page_source.replace('#', '$-$')
page_source = page_source.replace('*', '$!$')
page_source = page_source.replace('%', '$p$')
#page_source = page_source.replace('<a href=', '$"$')
#page_source = page_source.replace("</a>", "$'$")
#page_source = page_source.replace('the', 't')
#page_source = page_source.replace('noscript', '$n$')
#page_source = page_source.replace('for', 'f')
#page_source = page_source.replace('with', 'w')
#page_source = page_source.replace('aria-hidden', '$a$')
#page_source = page_source.replace('this', '$t$')
#page_source = page_source.replace('<script', '$s$')
#page_source = page_source.replace("</script>", "$st$")
#page_source = page_source.replace('<meta', '$m$')
#page_source = page_source.replace('<blockquote>', '$b$')
page_source = page_source.replace('é', 'e')
page_source = page_source.replace('à', 'a')
page_source = page_source.replace('ï', 'i')
page_source = page_source.replace('è', 'e')
#os.system('> encoded.html')
text_file = open("encoded.html", "w")
text_file.write("{0}".format(page_source))
text_file.close()
#### Debug mode
#print(page_source)
# Encoding the HTML to CW_Morse using cwwav
os.system('../cwwav-master/cwwav encoded.html --output encoded.wav')
# Playing the audio file
os.system('/mnt/c/Program\ Files/VideoLAN/VLC/vlc.exe --play-and-exit encoded.wav')
os.system('rm encode.html && rm encoded.html && rm source.html && rm sourceorig.html')
